cargo run -r -- -d ./testcases/1.out
cargo run -r -- -m ./testcases/1.out
cargo run -r -- -d ./testcases/2.out
cargo run -r -- -m ./testcases/2.out
cargo run -r -- -d ./testcases/3.out
cargo run -r -- -m ./testcases/3.out
cargo run -r -- -d ./testcases/4.out
cargo run -r -- -m ./testcases/4.out
cargo run -r -- -d ./testcases/5.out
cargo run -r -- -m ./testcases/5.out
cargo run -r -- -d ./testcases/6.out
cargo run -r -- -m ./testcases/6.out
cargo run -r -- -d ./testcases/7.out
cargo run -r -- -m ./testcases/7.out
